fakestore:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'FAKESTORE_ROLE') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'FAKESTORE_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'FAKESTORE_DB') }}"
      schema: RAW
      threads: 4
