-- ============================================================================
-- Snowflake Setup (run once as ACCOUNTADMIN)
-- Creates role, warehouse, database, schemas, tables.
-- ============================================================================

-- Service User creation 
USE ROLE ACCOUNTADMIN;

CREATE USER IF NOT EXISTS FAKESTORE_USER
    PASSWORD = 'Saurabhsuman2026_'
    DEFAULT_ROLE = FAKESTORE_ROLE
    DEFAULT_WAREHOUSE = FAKESTORE_WH
    DEFAULT_NAMESPACE = FAKESTORE_DB
    MUST_CHANGE_PASSWORD = FALSE
    COMMENT = 'Service account for the fakestore data pipeline';

--  Create a role for the pipeline
CREATE ROLE IF NOT EXISTS FAKESTORE_ROLE;
GRANT ROLE FAKESTORE_ROLE TO ROLE SYSADMIN;

--  Assign the role to the pipeline user AND the admin user
GRANT ROLE FAKESTORE_ROLE TO USER FAKESTORE_USER;
GRANT ROLE FAKESTORE_ROLE TO USER suman373;

--  Warehouse creation
CREATE WAREHOUSE IF NOT EXISTS FAKESTORE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE FAKESTORE_WH TO ROLE FAKESTORE_ROLE;

--  Database and schemas
CREATE DATABASE IF NOT EXISTS FAKESTORE_DB;
GRANT OWNERSHIP ON DATABASE FAKESTORE_DB TO ROLE FAKESTORE_ROLE;

USE ROLE FAKESTORE_ROLE;
USE DATABASE FAKESTORE_DB;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS BUSINESS;
CREATE SCHEMA IF NOT EXISTS ML;

-- Grant permissions on schemas
USE ROLE ACCOUNTADMIN;
GRANT ALL ON SCHEMA FAKESTORE_DB.RAW       TO ROLE FAKESTORE_ROLE;
GRANT ALL ON SCHEMA FAKESTORE_DB.STAGING   TO ROLE FAKESTORE_ROLE;
GRANT ALL ON SCHEMA FAKESTORE_DB.BUSINESS  TO ROLE FAKESTORE_ROLE;
GRANT ALL ON SCHEMA FAKESTORE_DB.ML        TO ROLE FAKESTORE_ROLE;

GRANT ALL ON FUTURE TABLES IN SCHEMA FAKESTORE_DB.RAW       TO ROLE FAKESTORE_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA FAKESTORE_DB.STAGING   TO ROLE FAKESTORE_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA FAKESTORE_DB.BUSINESS  TO ROLE FAKESTORE_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA FAKESTORE_DB.ML        TO ROLE FAKESTORE_ROLE;

GRANT ALL ON FUTURE VIEWS IN SCHEMA FAKESTORE_DB.STAGING    TO ROLE FAKESTORE_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA FAKESTORE_DB.BUSINESS   TO ROLE FAKESTORE_ROLE;
GRANT ALL ON FUTURE VIEWS IN SCHEMA FAKESTORE_DB.ML         TO ROLE FAKESTORE_ROLE;


